/*
  PROBLEM 031
  How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/

export const coinCombinations = (pound: number) => {
  const COINS = [1, 2, 5, 10, 20, 50, 100, 200];
  const pence = pound * 100;

  const combos = (p: number, combos: number[] = []): number[] => {
    
    return combos;
  };

  return combos(pence).length;
};
